name: Build Eleventy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install elm
        run: yarn global add elm

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: 1.46.0

      - name: Install TSC globally
        run: yarn global add typescript

      - name: Install dependencies
        run: yarn

      - name: Build
        run: node main.js

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./output
          github_token: ${{ secrets.GITHUB_TOKEN }}
