name: Build Eleventy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Setup | Elm
        run: yarn global add elm

      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: 1.46.0

      - name: Setup | TSC
        run: yarn global add typescript

      - uses: fwal/setup-swift@v1

      - name: Setup | ReScript
        run: yarn global add bs-platform

      - name: Install dependencies
        run: yarn

      - name: Build Examples
        run: yarn generate

      - name: Echo output
        run: |
          sudo apt-get install tree
          tree output

      - name: Build Site
        run: yarn build-site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}
